<?php

declare(strict_types=1);

use App\Actions\Pages\RecordPageRevision;
use App\Models\Page;
use App\Models\PageRevision;
use App\Models\Tenant;
use App\Models\User;

function revisionBlocks(string $heading = 'Welcome'): array
{
    return [['type' => 'hero', 'data' => ['variant' => 'centered-minimal', 'heading' => $heading]]];
}

function recordRevision(Tenant $tenant, Page $page, array $blocks, ?User $user = null): ?PageRevision
{
    return test()->runInTenant(
        $tenant,
        fn (): ?PageRevision => resolve(RecordPageRevision::class)->handle($page, $blocks, $user),
    );
}

it('seeds the state it is replacing, so a first save is still undoable', function (): void {
    // Without this the history starts at "after your first save" and whatever the
    // page held before — an AI-generated draft, an import — is the one version
    // that can never be recovered.
    $tenant = Tenant::factory()->create();
    $page = $this->createTenantPage($tenant, revisionBlocks('Generated by AI'));
    $user = User::factory()->create();

    recordRevision($tenant, $page, revisionBlocks('Rewritten by hand'), $user);

    $history = PageRevision::query()->orderBy('id')->get();

    expect($history)->toHaveCount(2)
        ->and($history[0]->blocks)->toBe(revisionBlocks('Generated by AI'))
        ->and($history[1]->blocks)->toBe(revisionBlocks('Rewritten by hand'))
        ->and($history[1]->user_id)->toBe($user->id)
        ->and($history[1]->tenant_id)->toBe($tenant->id);
});

it('adds one version per subsequent save', function (): void {
    $tenant = Tenant::factory()->create();
    $page = $this->createTenantPage($tenant, revisionBlocks('One'));

    recordRevision($tenant, $page, revisionBlocks('Two'));
    recordRevision($tenant, $page, revisionBlocks('Three'));

    expect(PageRevision::query()->orderBy('id')->pluck('blocks')->map(
        fn (array $blocks): string => $blocks[0]['data']['heading'],
    )->all())->toBe(['One', 'Two', 'Three']);
});

it('does not manufacture a version when the blocks did not change', function (): void {
    // A chrome-only edit, or a second click on Save. A spurious row would push a
    // real one out of the window.
    $tenant = Tenant::factory()->create();
    $page = $this->createTenantPage($tenant, revisionBlocks('One'));

    recordRevision($tenant, $page, revisionBlocks('Two'));

    expect(recordRevision($tenant, $page, revisionBlocks('Two')))->toBeNull()
        ->and(PageRevision::query()->count())->toBe(2);
});

it('keeps only the most recent versions', function (): void {
    $tenant = Tenant::factory()->create();
    $page = $this->createTenantPage($tenant, revisionBlocks('start'));

    foreach (range(1, RecordPageRevision::LIMIT + 5) as $i) {
        recordRevision($tenant, $page, revisionBlocks('v'.$i));
    }

    $history = PageRevision::query()->orderBy('id')->get();

    expect($history)->toHaveCount(RecordPageRevision::LIMIT)
        // The oldest were dropped; the newest survives.
        ->and($history->last()->blocks[0]['data']['heading'])->toBe('v'.(RecordPageRevision::LIMIT + 5));
});

it('keeps each page history separate', function (): void {
    $tenant = Tenant::factory()->create();
    $home = $this->createTenantPage($tenant, revisionBlocks('home'));
    $about = $this->createTenantPage($tenant, revisionBlocks('about'), 'about');

    recordRevision($tenant, $home, revisionBlocks('home edited'));
    recordRevision($tenant, $about, revisionBlocks('about edited'));

    expect(PageRevision::query()->where('page_id', $home->id)->count())->toBe(2)
        ->and(PageRevision::query()->where('page_id', $about->id)->count())->toBe(2);
});

it('drops structurally broken stored blocks when seeding', function (): void {
    // pages.blocks is written by seeders and AI drafts as well as the editor, so
    // the seeded revision is normalised rather than trusted.
    $tenant = Tenant::factory()->create();
    $page = $this->createTenantPage($tenant, [
        'not an array',
        ['data' => ['heading' => 'no type']],
        ['type' => 'hero', 'data' => 'not an array'],
        ['type' => 'cta', 'data' => [0 => 'numeric key']],
    ]);

    recordRevision($tenant, $page, revisionBlocks('after'));

    expect(PageRevision::query()->orderBy('id')->first()->blocks)->toBe([
        ['type' => 'hero', 'data' => []],
        ['type' => 'cta', 'data' => ['0' => 'numeric key']],
    ]);
});
