<?php

declare(strict_types=1);

namespace App\Filament\Fabricator\PageBlocks;

use App\Site\Blocks\BlockIntent;
use Filament\Forms\Components\Field;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Support\Icons\Heroicon;

/**
 * An ordered process: how an enquiry becomes a booking, what happens on the day.
 *
 * The block that {@see Features} was being abused for. Both present as "a
 * heading plus a repeater of titled items", so nothing in their FIELDS separates
 * them. The distinction is ORDER: a features list reads the same shuffled, a
 * process does not.
 *
 * The numbers are generated by the view from the item's position, never
 * authored. An operator who types "1." into a title has a page that lies the
 * moment they delete step two — and deleting a step mid-list is exactly what a
 * process block is edited for.
 */
final class Steps extends Block
{
    protected static string $name = 'steps';

    protected static string $description = 'What happens next, in order — how an enquiry becomes a booking, how a job gets done, what a first visit is like. Use it only when the ORDER matters; for unordered reasons to choose the business, use features instead.';

    protected static ?Heroicon $icon = Heroicon::OutlinedNumberedList;

    protected static ?BlockIntent $intent = BlockIntent::Showcase;

    /**
     * @var array<string, mixed>
     */
    protected static array $sample = [
        'heading' => 'How it works',
        'intro' => 'Three steps from first contact to finished job — replace them with your own.',
        'steps' => [
            ['title' => 'Get in touch', 'description' => 'Replace this with what the customer does first.'],
            ['title' => 'We plan it together', 'description' => 'Replace this with what happens next.'],
            ['title' => 'The work gets done', 'description' => 'Replace this with how it finishes.'],
        ],
    ];

    /**
     * @return array<int, Field>
     */
    protected static function fields(): array
    {
        return [
            TextInput::make('heading')
                ->maxLength(200),
            Textarea::make('intro')
                ->rows(2)
                ->maxLength(500),
            Repeater::make('steps')
                ->schema([
                    TextInput::make('title')
                        ->required()
                        ->maxLength(120),
                    Textarea::make('description')
                        ->rows(2)
                        ->maxLength(500),
                ])
                ->addActionLabel('Add step')
                ->helperText('Numbered automatically, in this order — do not type the numbers yourself.'),
        ];
    }
}
